//
//  DiscussionTopic.swift
//  MMCoach
//

import Foundation

/// One item in the "Be Prepared to Discuss" section, generated by
/// mmFinalizeCase. Kept neutral and educational -- this is not a list of
/// findings or faults.
struct DiscussionTopic: Codable, Hashable {
    let topic: String
    let whyItMatters: String
    let prepareToDiscuss: String
}
