package dev.benderapps.mmcoach.models

/** Mirrors the backend's `collecting_information` / `ready_to_finalize` / `completed` state machine. */
enum class CaseStatus(val wireValue: String) {
    COLLECTING_INFORMATION("collecting_information"),
    READY_TO_FINALIZE("ready_to_finalize"),
    COMPLETED("completed");

    companion object {
        fun fromWireValue(value: String): CaseStatus =
            entries.first { it.wireValue == value }
    }
}

/** A single AI-generated follow-up question, as returned in `nextQuestion`. */
data class MMQuestion(
    val id: String,
    val text: String,
    val category: String,
    val reason: String,
)

/** One item in the "Be Prepared to Discuss" section, generated by mmFinalizeCase. */
data class DiscussionTopic(
    val topic: String,
    val whyItMatters: String,
    val prepareToDiscuss: String,
)

/** A literature/guideline topic identified by the backend as relevant to the case. */
data class ReferenceItem(
    val topic: String,
    val searchIntent: String,
    val citation: String?,
    val verified: Boolean,
)

/**
 * Client-side representation of an M&M case-preparation session. Mirrors
 * iOS `Models/MMCase.swift` -- the single response shape shared by
 * mmCreateCase, mmAnswerQuestion, mmFinalizeCase, and mmGetCase.
 */
data class MMCase(
    val id: String,
    val status: CaseStatus,
    val nextQuestion: MMQuestion? = null,
    val polishedNarrative: String? = null,
    val discussionPreparation: List<DiscussionTopic> = emptyList(),
    val likelyFacultyQuestions: List<String> = emptyList(),
    val references: List<ReferenceItem> = emptyList(),
)
